const express = require("express");
const userRoute = require("./userRoute");
const categoryRoute = require("./categoryRoute");
const ordersRoute = require("../routes/ordersRoute");
const customerRoute = require("./customerRoute");
const subcategoryRoute = require("./subcategoryRoute");
const productRoute = require("../routes/productRoute");
const homeRoute = require("../routes/homeRoute");
const reviewRoute = require("../routes/reviewRoute");
const paymentRoute = require("../routes/paymentRoute");
const notificationRoute = require("../routes/notificationRoute");
const couponRoute = require("../routes/couponRoute");
const contactRoute = require("../routes/contactRoute");
const settingsRoute = require("../routes/siteSettingsRoute");
const vendorRoute = require("../routes/vendorRoutes");
const dashboardRoute = require("../routes/dashboardRoute");
const dashboardNotificationRoute = require("../routes/dashboardNotificationRoute");
const localizationRoute = require("./localizationRoutes");
const localeRoute = require("./localeRoute");
const app = express();
const apicache = require("apicache");
const cache = apicache.middleware;

app.use("/v1/products", cache("5 minutes"), productRoute);
app.use("/v1/categories", cache("5 minutes"), categoryRoute);
app.use("/v1/subcategories", cache("5 minutes"), subcategoryRoute);
app.use("/v1/site-settings", settingsRoute);
app.use("/v1/reviews", reviewRoute);
app.use("/v1/customers", customerRoute);
app.use("/v1/payments", paymentRoute);
app.use("/v1/vendors", vendorRoute);
app.use("/v1/", homeRoute);
app.use("/v1/coupons", couponRoute);
app.use("/v1/contact", contactRoute);
app.use("/v1/orders", ordersRoute);
app.use("/v1/users", userRoute);
app.use("/v1/notifications", notificationRoute);
app.use("/v1/dashboard", dashboardRoute);
app.use("/v1/dashboard-notifications", dashboardNotificationRoute);
app.use("/v1/localization", localizationRoute);
app.use("/v1/locales", localeRoute);

module.exports = app;
